# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db9638b10da97920149d2ede2d47d6138708662a755e66f62d6ed22552ba2f43b41f11c4e5db79ea01e22c3261f69cda3ecc011d87d9361e314dcaa326f6d040

test:
  secret_key_base: 7b2f21d4d57475e2f48ceddd36786693f302b7352c19eec23835dea064a20d1a74a1125005b5d6e9230c39ce48161d4f2804f218a125578859fec5401c8c0590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
